image: Visual Studio 2022

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

services:
  - postgresql10
  - mssql2017
  - mysql

environment:
  MYSQL: Server=localhost;Database=migr8_test;Uid=root;Pwd=Password12!;

before_build:
  - ps: $env:MYSQL_PWD="Password12!"
  - ps: $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database migr8_test;" --user=root'
  - ps: iex "& $cmd"
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET SQLSERVER=server=(local)\SQL2017;database=migr8_test;User ID=sa;Password=Password12!;encrypt=false
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb migr8_test
  - sqlcmd -S "(local)\SQL2017" -U "sa" -P "Password12!" -Q "CREATE DATABASE migr8_test;" -d "master"
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build migr8.sln -c Release 

test_script:
  - dotnet test